### ISSUE TITLE
Signature is missing

### ISSUE THREAD

**Issue by anthonybourdon** [AXN-Informatique/laravel-glide#6]
Signature is missing.
When we want use the imageAsBase64() method, there is a validation of the sign_key. But we can't validate this key and it's not necessary to validate.
I think this problem is in methods outputImage and imageResponse to.

**Comment by mefenlon** [comment]
@anthonybourdon did you ever find a solution for this?

**Comment by anthonybourdon** [comment]
@mefenlon , for the moment, you can skip the validation of the sign_key by adding a third parameter to 'true' to the three methods  imageAsBase64, outputImage, imageResponse

**Comment by forxer** [comment]
This has been fixed in version 2. But this requires Laravel 9. We have removed this third parameter.

Be careful for imageResponse() the validation is strongly advised, you should rather configure the key well for the Glide server.
